# European languages
LATIN_LANGS = [
    ('sq', 'Albanian'),
    ('bs', 'Bosnian'),
    ('bg', 'Bulgarian'),
    ('hr', 'Croatian'),
    ('cs', 'Czech'),
    ('da', 'Danish'),
    ('nl', 'Dutch'),
    ('en', 'English'),
    ('et', 'Estonian'),
    ('fi', 'Finnish'),
    ('fr', 'French'),
    ('de', 'German'),
    ('el', 'Greek'),
    ('ga', 'Irish'),
    ('is', 'Icelandic'),
    ('hu', 'Hungarian'),
    ('lv', 'Latvian'),
    ('lt', 'Lithuanian'),
    ('mk', 'Macedonian'),
    ('mt', 'Maltese'),
    ('no', 'Norwegian'),
    ('pl', 'Polish'),
    ('pt', 'Portuguese'),
    ('ro', 'Romanian'),
    ('sr', 'Serbian'),
    ('sk', 'Slovak'),
    ('sl', 'Slovenian'),
    ('es', 'Spanish'),
    ('sv', 'Swedish'),
    ('tr', 'Turkish')
]

NON_LATIN_LANGS = [
    ('hi', 'Hindi'),
    ('ar', 'Arabic'),
    ('fa', 'Persian'),
    ('ur', 'Urdu'),
    ('sw', 'Swahili'),
    ('pa', 'Punjabi'),
    ('bn', 'Bengali'),
    ('ru', 'Russian'),
    ('ja', 'Japanese'),
    ('ko', 'Korean'),
    ('th', 'Thai'),
    ('zh-CN', 'Chinese'),
    ('uk', 'Ukrainian'),
]